# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kirby/Programming/NebulaInject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kirby/Programming/NebulaInject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kirby/Programming/NebulaInject/CMakeFiles /home/kirby/Programming/NebulaInject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kirby/Programming/NebulaInject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phantom

# Build rule for target.
phantom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phantom
.PHONY : phantom

# fast build rule for target.
phantom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/build
.PHONY : phantom/fast

src/Phantom.o: src/Phantom.cpp.o
.PHONY : src/Phantom.o

# target to build an object file
src/Phantom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/Phantom.cpp.o
.PHONY : src/Phantom.cpp.o

src/Phantom.i: src/Phantom.cpp.i
.PHONY : src/Phantom.i

# target to preprocess a source file
src/Phantom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/Phantom.cpp.i
.PHONY : src/Phantom.cpp.i

src/Phantom.s: src/Phantom.cpp.s
.PHONY : src/Phantom.s

# target to generate assembly for a file
src/Phantom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/Phantom.cpp.s
.PHONY : src/Phantom.cpp.s

src/cheats/Cheat.o: src/cheats/Cheat.cpp.o
.PHONY : src/cheats/Cheat.o

# target to build an object file
src/cheats/Cheat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/Cheat.cpp.o
.PHONY : src/cheats/Cheat.cpp.o

src/cheats/Cheat.i: src/cheats/Cheat.cpp.i
.PHONY : src/cheats/Cheat.i

# target to preprocess a source file
src/cheats/Cheat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/Cheat.cpp.i
.PHONY : src/cheats/Cheat.cpp.i

src/cheats/Cheat.s: src/cheats/Cheat.cpp.s
.PHONY : src/cheats/Cheat.s

# target to generate assembly for a file
src/cheats/Cheat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/Cheat.cpp.s
.PHONY : src/cheats/Cheat.cpp.s

src/cheats/FastPlace.o: src/cheats/FastPlace.cpp.o
.PHONY : src/cheats/FastPlace.o

# target to build an object file
src/cheats/FastPlace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/FastPlace.cpp.o
.PHONY : src/cheats/FastPlace.cpp.o

src/cheats/FastPlace.i: src/cheats/FastPlace.cpp.i
.PHONY : src/cheats/FastPlace.i

# target to preprocess a source file
src/cheats/FastPlace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/FastPlace.cpp.i
.PHONY : src/cheats/FastPlace.cpp.i

src/cheats/FastPlace.s: src/cheats/FastPlace.cpp.s
.PHONY : src/cheats/FastPlace.s

# target to generate assembly for a file
src/cheats/FastPlace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/cheats/FastPlace.cpp.s
.PHONY : src/cheats/FastPlace.cpp.s

src/library.o: src/library.cpp.o
.PHONY : src/library.o

# target to build an object file
src/library.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/library.cpp.o
.PHONY : src/library.cpp.o

src/library.i: src/library.cpp.i
.PHONY : src/library.i

# target to preprocess a source file
src/library.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/library.cpp.i
.PHONY : src/library.cpp.i

src/library.s: src/library.cpp.s
.PHONY : src/library.s

# target to generate assembly for a file
src/library.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/library.cpp.s
.PHONY : src/library.cpp.s

src/mapping/AbstractClass.o: src/mapping/AbstractClass.cpp.o
.PHONY : src/mapping/AbstractClass.o

# target to build an object file
src/mapping/AbstractClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/AbstractClass.cpp.o
.PHONY : src/mapping/AbstractClass.cpp.o

src/mapping/AbstractClass.i: src/mapping/AbstractClass.cpp.i
.PHONY : src/mapping/AbstractClass.i

# target to preprocess a source file
src/mapping/AbstractClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/AbstractClass.cpp.i
.PHONY : src/mapping/AbstractClass.cpp.i

src/mapping/AbstractClass.s: src/mapping/AbstractClass.cpp.s
.PHONY : src/mapping/AbstractClass.s

# target to generate assembly for a file
src/mapping/AbstractClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/AbstractClass.cpp.s
.PHONY : src/mapping/AbstractClass.cpp.s

src/mapping/Mapping.o: src/mapping/Mapping.cpp.o
.PHONY : src/mapping/Mapping.o

# target to build an object file
src/mapping/Mapping.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/Mapping.cpp.o
.PHONY : src/mapping/Mapping.cpp.o

src/mapping/Mapping.i: src/mapping/Mapping.cpp.i
.PHONY : src/mapping/Mapping.i

# target to preprocess a source file
src/mapping/Mapping.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/Mapping.cpp.i
.PHONY : src/mapping/Mapping.cpp.i

src/mapping/Mapping.s: src/mapping/Mapping.cpp.s
.PHONY : src/mapping/Mapping.s

# target to generate assembly for a file
src/mapping/Mapping.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/Mapping.cpp.s
.PHONY : src/mapping/Mapping.cpp.s

src/mapping/impl/java/io/JavaPrintStream.o: src/mapping/impl/java/io/JavaPrintStream.cpp.o
.PHONY : src/mapping/impl/java/io/JavaPrintStream.o

# target to build an object file
src/mapping/impl/java/io/JavaPrintStream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/io/JavaPrintStream.cpp.o
.PHONY : src/mapping/impl/java/io/JavaPrintStream.cpp.o

src/mapping/impl/java/io/JavaPrintStream.i: src/mapping/impl/java/io/JavaPrintStream.cpp.i
.PHONY : src/mapping/impl/java/io/JavaPrintStream.i

# target to preprocess a source file
src/mapping/impl/java/io/JavaPrintStream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/io/JavaPrintStream.cpp.i
.PHONY : src/mapping/impl/java/io/JavaPrintStream.cpp.i

src/mapping/impl/java/io/JavaPrintStream.s: src/mapping/impl/java/io/JavaPrintStream.cpp.s
.PHONY : src/mapping/impl/java/io/JavaPrintStream.s

# target to generate assembly for a file
src/mapping/impl/java/io/JavaPrintStream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/io/JavaPrintStream.cpp.s
.PHONY : src/mapping/impl/java/io/JavaPrintStream.cpp.s

src/mapping/impl/java/lang/JavaSystem.o: src/mapping/impl/java/lang/JavaSystem.cpp.o
.PHONY : src/mapping/impl/java/lang/JavaSystem.o

# target to build an object file
src/mapping/impl/java/lang/JavaSystem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/lang/JavaSystem.cpp.o
.PHONY : src/mapping/impl/java/lang/JavaSystem.cpp.o

src/mapping/impl/java/lang/JavaSystem.i: src/mapping/impl/java/lang/JavaSystem.cpp.i
.PHONY : src/mapping/impl/java/lang/JavaSystem.i

# target to preprocess a source file
src/mapping/impl/java/lang/JavaSystem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/lang/JavaSystem.cpp.i
.PHONY : src/mapping/impl/java/lang/JavaSystem.cpp.i

src/mapping/impl/java/lang/JavaSystem.s: src/mapping/impl/java/lang/JavaSystem.cpp.s
.PHONY : src/mapping/impl/java/lang/JavaSystem.s

# target to generate assembly for a file
src/mapping/impl/java/lang/JavaSystem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/lang/JavaSystem.cpp.s
.PHONY : src/mapping/impl/java/lang/JavaSystem.cpp.s

src/mapping/impl/java/util/JavaList.o: src/mapping/impl/java/util/JavaList.cpp.o
.PHONY : src/mapping/impl/java/util/JavaList.o

# target to build an object file
src/mapping/impl/java/util/JavaList.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaList.cpp.o
.PHONY : src/mapping/impl/java/util/JavaList.cpp.o

src/mapping/impl/java/util/JavaList.i: src/mapping/impl/java/util/JavaList.cpp.i
.PHONY : src/mapping/impl/java/util/JavaList.i

# target to preprocess a source file
src/mapping/impl/java/util/JavaList.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaList.cpp.i
.PHONY : src/mapping/impl/java/util/JavaList.cpp.i

src/mapping/impl/java/util/JavaList.s: src/mapping/impl/java/util/JavaList.cpp.s
.PHONY : src/mapping/impl/java/util/JavaList.s

# target to generate assembly for a file
src/mapping/impl/java/util/JavaList.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaList.cpp.s
.PHONY : src/mapping/impl/java/util/JavaList.cpp.s

src/mapping/impl/java/util/JavaSet.o: src/mapping/impl/java/util/JavaSet.cpp.o
.PHONY : src/mapping/impl/java/util/JavaSet.o

# target to build an object file
src/mapping/impl/java/util/JavaSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaSet.cpp.o
.PHONY : src/mapping/impl/java/util/JavaSet.cpp.o

src/mapping/impl/java/util/JavaSet.i: src/mapping/impl/java/util/JavaSet.cpp.i
.PHONY : src/mapping/impl/java/util/JavaSet.i

# target to preprocess a source file
src/mapping/impl/java/util/JavaSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaSet.cpp.i
.PHONY : src/mapping/impl/java/util/JavaSet.cpp.i

src/mapping/impl/java/util/JavaSet.s: src/mapping/impl/java/util/JavaSet.cpp.s
.PHONY : src/mapping/impl/java/util/JavaSet.s

# target to generate assembly for a file
src/mapping/impl/java/util/JavaSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/java/util/JavaSet.cpp.s
.PHONY : src/mapping/impl/java/util/JavaSet.cpp.s

src/mapping/impl/net/minecraft/client/Minecraft.o: src/mapping/impl/net/minecraft/client/Minecraft.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.o

# target to build an object file
src/mapping/impl/net/minecraft/client/Minecraft.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/Minecraft.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.cpp.o

src/mapping/impl/net/minecraft/client/Minecraft.i: src/mapping/impl/net/minecraft/client/Minecraft.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/client/Minecraft.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/Minecraft.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.cpp.i

src/mapping/impl/net/minecraft/client/Minecraft.s: src/mapping/impl/net/minecraft/client/Minecraft.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/client/Minecraft.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/Minecraft.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/Minecraft.cpp.s

src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.o: src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.o

# target to build an object file
src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.o

src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.i: src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.i

src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.s: src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.cpp.s

src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.o: src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.o

# target to build an object file
src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.o

src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.i: src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.i

src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.s: src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.cpp.s

src/mapping/impl/net/minecraft/client/settings/GameSettings.o: src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.o

# target to build an object file
src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.o

src/mapping/impl/net/minecraft/client/settings/GameSettings.i: src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.i

src/mapping/impl/net/minecraft/client/settings/GameSettings.s: src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/settings/GameSettings.cpp.s

src/mapping/impl/net/minecraft/client/settings/KeyBinding.o: src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.o

# target to build an object file
src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.o
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.o

src/mapping/impl/net/minecraft/client/settings/KeyBinding.i: src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.i
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.i

src/mapping/impl/net/minecraft/client/settings/KeyBinding.s: src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.s
.PHONY : src/mapping/impl/net/minecraft/client/settings/KeyBinding.cpp.s

src/mapping/impl/net/minecraft/entity/Entity.o: src/mapping/impl/net/minecraft/entity/Entity.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.o

# target to build an object file
src/mapping/impl/net/minecraft/entity/Entity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/Entity.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.cpp.o

src/mapping/impl/net/minecraft/entity/Entity.i: src/mapping/impl/net/minecraft/entity/Entity.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/entity/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/Entity.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.cpp.i

src/mapping/impl/net/minecraft/entity/Entity.s: src/mapping/impl/net/minecraft/entity/Entity.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/entity/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/Entity.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/Entity.cpp.s

src/mapping/impl/net/minecraft/entity/EntityLivingBase.o: src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.o

# target to build an object file
src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.o

src/mapping/impl/net/minecraft/entity/EntityLivingBase.i: src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.i

src/mapping/impl/net/minecraft/entity/EntityLivingBase.s: src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/EntityLivingBase.cpp.s

src/mapping/impl/net/minecraft/entity/EntityPlayerSP.o: src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.o

# target to build an object file
src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.o

src/mapping/impl/net/minecraft/entity/EntityPlayerSP.i: src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.i

src/mapping/impl/net/minecraft/entity/EntityPlayerSP.s: src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/EntityPlayerSP.cpp.s

src/mapping/impl/net/minecraft/entity/player/EntityPlayer.o: src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.o

# target to build an object file
src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.o

src/mapping/impl/net/minecraft/entity/player/EntityPlayer.i: src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.i

src/mapping/impl/net/minecraft/entity/player/EntityPlayer.s: src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/entity/player/EntityPlayer.cpp.s

src/mapping/impl/net/minecraft/util/AxisAlignedBB.o: src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.o

# target to build an object file
src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.o

src/mapping/impl/net/minecraft/util/AxisAlignedBB.i: src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.i

src/mapping/impl/net/minecraft/util/AxisAlignedBB.s: src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/AxisAlignedBB.cpp.s

src/mapping/impl/net/minecraft/util/MovingObjectPosition.o: src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.o

# target to build an object file
src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.o

src/mapping/impl/net/minecraft/util/MovingObjectPosition.i: src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.i

src/mapping/impl/net/minecraft/util/MovingObjectPosition.s: src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/MovingObjectPosition.cpp.s

src/mapping/impl/net/minecraft/util/Timer.o: src/mapping/impl/net/minecraft/util/Timer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/Timer.o

# target to build an object file
src/mapping/impl/net/minecraft/util/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Timer.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/Timer.cpp.o

src/mapping/impl/net/minecraft/util/Timer.i: src/mapping/impl/net/minecraft/util/Timer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/Timer.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/util/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Timer.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/Timer.cpp.i

src/mapping/impl/net/minecraft/util/Timer.s: src/mapping/impl/net/minecraft/util/Timer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/Timer.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/util/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Timer.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/Timer.cpp.s

src/mapping/impl/net/minecraft/util/Vec3.o: src/mapping/impl/net/minecraft/util/Vec3.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.o

# target to build an object file
src/mapping/impl/net/minecraft/util/Vec3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Vec3.cpp.o
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.cpp.o

src/mapping/impl/net/minecraft/util/Vec3.i: src/mapping/impl/net/minecraft/util/Vec3.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.i

# target to preprocess a source file
src/mapping/impl/net/minecraft/util/Vec3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Vec3.cpp.i
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.cpp.i

src/mapping/impl/net/minecraft/util/Vec3.s: src/mapping/impl/net/minecraft/util/Vec3.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.s

# target to generate assembly for a file
src/mapping/impl/net/minecraft/util/Vec3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/net/minecraft/util/Vec3.cpp.s
.PHONY : src/mapping/impl/net/minecraft/util/Vec3.cpp.s

src/mapping/impl/org/lwjgl/input/Mouse.o: src/mapping/impl/org/lwjgl/input/Mouse.cpp.o
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.o

# target to build an object file
src/mapping/impl/org/lwjgl/input/Mouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/org/lwjgl/input/Mouse.cpp.o
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.cpp.o

src/mapping/impl/org/lwjgl/input/Mouse.i: src/mapping/impl/org/lwjgl/input/Mouse.cpp.i
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.i

# target to preprocess a source file
src/mapping/impl/org/lwjgl/input/Mouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/org/lwjgl/input/Mouse.cpp.i
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.cpp.i

src/mapping/impl/org/lwjgl/input/Mouse.s: src/mapping/impl/org/lwjgl/input/Mouse.cpp.s
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.s

# target to generate assembly for a file
src/mapping/impl/org/lwjgl/input/Mouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/mapping/impl/org/lwjgl/input/Mouse.cpp.s
.PHONY : src/mapping/impl/org/lwjgl/input/Mouse.cpp.s

src/ui/KeyManager.o: src/ui/KeyManager.cpp.o
.PHONY : src/ui/KeyManager.o

# target to build an object file
src/ui/KeyManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/KeyManager.cpp.o
.PHONY : src/ui/KeyManager.cpp.o

src/ui/KeyManager.i: src/ui/KeyManager.cpp.i
.PHONY : src/ui/KeyManager.i

# target to preprocess a source file
src/ui/KeyManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/KeyManager.cpp.i
.PHONY : src/ui/KeyManager.cpp.i

src/ui/KeyManager.s: src/ui/KeyManager.cpp.s
.PHONY : src/ui/KeyManager.s

# target to generate assembly for a file
src/ui/KeyManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/KeyManager.cpp.s
.PHONY : src/ui/KeyManager.cpp.s

src/ui/PhantomWindow.o: src/ui/PhantomWindow.cpp.o
.PHONY : src/ui/PhantomWindow.o

# target to build an object file
src/ui/PhantomWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/PhantomWindow.cpp.o
.PHONY : src/ui/PhantomWindow.cpp.o

src/ui/PhantomWindow.i: src/ui/PhantomWindow.cpp.i
.PHONY : src/ui/PhantomWindow.i

# target to preprocess a source file
src/ui/PhantomWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/PhantomWindow.cpp.i
.PHONY : src/ui/PhantomWindow.cpp.i

src/ui/PhantomWindow.s: src/ui/PhantomWindow.cpp.s
.PHONY : src/ui/PhantomWindow.s

# target to generate assembly for a file
src/ui/PhantomWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/ui/PhantomWindow.cpp.s
.PHONY : src/ui/PhantomWindow.cpp.s

src/utils/ImGuiUtils.o: src/utils/ImGuiUtils.cpp.o
.PHONY : src/utils/ImGuiUtils.o

# target to build an object file
src/utils/ImGuiUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/ImGuiUtils.cpp.o
.PHONY : src/utils/ImGuiUtils.cpp.o

src/utils/ImGuiUtils.i: src/utils/ImGuiUtils.cpp.i
.PHONY : src/utils/ImGuiUtils.i

# target to preprocess a source file
src/utils/ImGuiUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/ImGuiUtils.cpp.i
.PHONY : src/utils/ImGuiUtils.cpp.i

src/utils/ImGuiUtils.s: src/utils/ImGuiUtils.cpp.s
.PHONY : src/utils/ImGuiUtils.s

# target to generate assembly for a file
src/utils/ImGuiUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/ImGuiUtils.cpp.s
.PHONY : src/utils/ImGuiUtils.cpp.s

src/utils/JvmUtils.o: src/utils/JvmUtils.cpp.o
.PHONY : src/utils/JvmUtils.o

# target to build an object file
src/utils/JvmUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/JvmUtils.cpp.o
.PHONY : src/utils/JvmUtils.cpp.o

src/utils/JvmUtils.i: src/utils/JvmUtils.cpp.i
.PHONY : src/utils/JvmUtils.i

# target to preprocess a source file
src/utils/JvmUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/JvmUtils.cpp.i
.PHONY : src/utils/JvmUtils.cpp.i

src/utils/JvmUtils.s: src/utils/JvmUtils.cpp.s
.PHONY : src/utils/JvmUtils.s

# target to generate assembly for a file
src/utils/JvmUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/JvmUtils.cpp.s
.PHONY : src/utils/JvmUtils.cpp.s

src/utils/MCUtils.o: src/utils/MCUtils.cpp.o
.PHONY : src/utils/MCUtils.o

# target to build an object file
src/utils/MCUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MCUtils.cpp.o
.PHONY : src/utils/MCUtils.cpp.o

src/utils/MCUtils.i: src/utils/MCUtils.cpp.i
.PHONY : src/utils/MCUtils.i

# target to preprocess a source file
src/utils/MCUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MCUtils.cpp.i
.PHONY : src/utils/MCUtils.cpp.i

src/utils/MCUtils.s: src/utils/MCUtils.cpp.s
.PHONY : src/utils/MCUtils.s

# target to generate assembly for a file
src/utils/MCUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MCUtils.cpp.s
.PHONY : src/utils/MCUtils.cpp.s

src/utils/MSTimer.o: src/utils/MSTimer.cpp.o
.PHONY : src/utils/MSTimer.o

# target to build an object file
src/utils/MSTimer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MSTimer.cpp.o
.PHONY : src/utils/MSTimer.cpp.o

src/utils/MSTimer.i: src/utils/MSTimer.cpp.i
.PHONY : src/utils/MSTimer.i

# target to preprocess a source file
src/utils/MSTimer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MSTimer.cpp.i
.PHONY : src/utils/MSTimer.cpp.i

src/utils/MSTimer.s: src/utils/MSTimer.cpp.s
.PHONY : src/utils/MSTimer.s

# target to generate assembly for a file
src/utils/MSTimer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MSTimer.cpp.s
.PHONY : src/utils/MSTimer.cpp.s

src/utils/MathHelper.o: src/utils/MathHelper.cpp.o
.PHONY : src/utils/MathHelper.o

# target to build an object file
src/utils/MathHelper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MathHelper.cpp.o
.PHONY : src/utils/MathHelper.cpp.o

src/utils/MathHelper.i: src/utils/MathHelper.cpp.i
.PHONY : src/utils/MathHelper.i

# target to preprocess a source file
src/utils/MathHelper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MathHelper.cpp.i
.PHONY : src/utils/MathHelper.cpp.i

src/utils/MathHelper.s: src/utils/MathHelper.cpp.s
.PHONY : src/utils/MathHelper.s

# target to generate assembly for a file
src/utils/MathHelper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MathHelper.cpp.s
.PHONY : src/utils/MathHelper.cpp.s

src/utils/MiscUtils.o: src/utils/MiscUtils.cpp.o
.PHONY : src/utils/MiscUtils.o

# target to build an object file
src/utils/MiscUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MiscUtils.cpp.o
.PHONY : src/utils/MiscUtils.cpp.o

src/utils/MiscUtils.i: src/utils/MiscUtils.cpp.i
.PHONY : src/utils/MiscUtils.i

# target to preprocess a source file
src/utils/MiscUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MiscUtils.cpp.i
.PHONY : src/utils/MiscUtils.cpp.i

src/utils/MiscUtils.s: src/utils/MiscUtils.cpp.s
.PHONY : src/utils/MiscUtils.s

# target to generate assembly for a file
src/utils/MiscUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/MiscUtils.cpp.s
.PHONY : src/utils/MiscUtils.cpp.s

src/utils/XUtils.o: src/utils/XUtils.cpp.o
.PHONY : src/utils/XUtils.o

# target to build an object file
src/utils/XUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/XUtils.cpp.o
.PHONY : src/utils/XUtils.cpp.o

src/utils/XUtils.i: src/utils/XUtils.cpp.i
.PHONY : src/utils/XUtils.i

# target to preprocess a source file
src/utils/XUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/XUtils.cpp.i
.PHONY : src/utils/XUtils.cpp.i

src/utils/XUtils.s: src/utils/XUtils.cpp.s
.PHONY : src/utils/XUtils.s

# target to generate assembly for a file
src/utils/XUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/src/utils/XUtils.cpp.s
.PHONY : src/utils/XUtils.cpp.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_impl_opengl3.o: vendor/imgui/imgui_impl_opengl3.cpp.o
.PHONY : vendor/imgui/imgui_impl_opengl3.o

# target to build an object file
vendor/imgui/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_opengl3.cpp.o
.PHONY : vendor/imgui/imgui_impl_opengl3.cpp.o

vendor/imgui/imgui_impl_opengl3.i: vendor/imgui/imgui_impl_opengl3.cpp.i
.PHONY : vendor/imgui/imgui_impl_opengl3.i

# target to preprocess a source file
vendor/imgui/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_opengl3.cpp.i
.PHONY : vendor/imgui/imgui_impl_opengl3.cpp.i

vendor/imgui/imgui_impl_opengl3.s: vendor/imgui/imgui_impl_opengl3.cpp.s
.PHONY : vendor/imgui/imgui_impl_opengl3.s

# target to generate assembly for a file
vendor/imgui/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_opengl3.cpp.s
.PHONY : vendor/imgui/imgui_impl_opengl3.cpp.s

vendor/imgui/imgui_impl_sdl.o: vendor/imgui/imgui_impl_sdl.cpp.o
.PHONY : vendor/imgui/imgui_impl_sdl.o

# target to build an object file
vendor/imgui/imgui_impl_sdl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_sdl.cpp.o
.PHONY : vendor/imgui/imgui_impl_sdl.cpp.o

vendor/imgui/imgui_impl_sdl.i: vendor/imgui/imgui_impl_sdl.cpp.i
.PHONY : vendor/imgui/imgui_impl_sdl.i

# target to preprocess a source file
vendor/imgui/imgui_impl_sdl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_sdl.cpp.i
.PHONY : vendor/imgui/imgui_impl_sdl.cpp.i

vendor/imgui/imgui_impl_sdl.s: vendor/imgui/imgui_impl_sdl.cpp.s
.PHONY : vendor/imgui/imgui_impl_sdl.s

# target to generate assembly for a file
vendor/imgui/imgui_impl_sdl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_impl_sdl.cpp.s
.PHONY : vendor/imgui/imgui_impl_sdl.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phantom.dir/build.make CMakeFiles/phantom.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... phantom"
	@echo "... src/Phantom.o"
	@echo "... src/Phantom.i"
	@echo "... src/Phantom.s"
	@echo "... src/cheats/Cheat.o"
	@echo "... src/cheats/Cheat.i"
	@echo "... src/cheats/Cheat.s"
	@echo "... src/cheats/FastPlace.o"
	@echo "... src/cheats/FastPlace.i"
	@echo "... src/cheats/FastPlace.s"
	@echo "... src/library.o"
	@echo "... src/library.i"
	@echo "... src/library.s"
	@echo "... src/mapping/AbstractClass.o"
	@echo "... src/mapping/AbstractClass.i"
	@echo "... src/mapping/AbstractClass.s"
	@echo "... src/mapping/Mapping.o"
	@echo "... src/mapping/Mapping.i"
	@echo "... src/mapping/Mapping.s"
	@echo "... src/mapping/impl/java/io/JavaPrintStream.o"
	@echo "... src/mapping/impl/java/io/JavaPrintStream.i"
	@echo "... src/mapping/impl/java/io/JavaPrintStream.s"
	@echo "... src/mapping/impl/java/lang/JavaSystem.o"
	@echo "... src/mapping/impl/java/lang/JavaSystem.i"
	@echo "... src/mapping/impl/java/lang/JavaSystem.s"
	@echo "... src/mapping/impl/java/util/JavaList.o"
	@echo "... src/mapping/impl/java/util/JavaList.i"
	@echo "... src/mapping/impl/java/util/JavaList.s"
	@echo "... src/mapping/impl/java/util/JavaSet.o"
	@echo "... src/mapping/impl/java/util/JavaSet.i"
	@echo "... src/mapping/impl/java/util/JavaSet.s"
	@echo "... src/mapping/impl/net/minecraft/client/Minecraft.o"
	@echo "... src/mapping/impl/net/minecraft/client/Minecraft.i"
	@echo "... src/mapping/impl/net/minecraft/client/Minecraft.s"
	@echo "... src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.o"
	@echo "... src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.i"
	@echo "... src/mapping/impl/net/minecraft/client/multiplayer/WorldClient.s"
	@echo "... src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.o"
	@echo "... src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.i"
	@echo "... src/mapping/impl/net/minecraft/client/renderer/EntityRenderer.s"
	@echo "... src/mapping/impl/net/minecraft/client/settings/GameSettings.o"
	@echo "... src/mapping/impl/net/minecraft/client/settings/GameSettings.i"
	@echo "... src/mapping/impl/net/minecraft/client/settings/GameSettings.s"
	@echo "... src/mapping/impl/net/minecraft/client/settings/KeyBinding.o"
	@echo "... src/mapping/impl/net/minecraft/client/settings/KeyBinding.i"
	@echo "... src/mapping/impl/net/minecraft/client/settings/KeyBinding.s"
	@echo "... src/mapping/impl/net/minecraft/entity/Entity.o"
	@echo "... src/mapping/impl/net/minecraft/entity/Entity.i"
	@echo "... src/mapping/impl/net/minecraft/entity/Entity.s"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityLivingBase.o"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityLivingBase.i"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityLivingBase.s"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityPlayerSP.o"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityPlayerSP.i"
	@echo "... src/mapping/impl/net/minecraft/entity/EntityPlayerSP.s"
	@echo "... src/mapping/impl/net/minecraft/entity/player/EntityPlayer.o"
	@echo "... src/mapping/impl/net/minecraft/entity/player/EntityPlayer.i"
	@echo "... src/mapping/impl/net/minecraft/entity/player/EntityPlayer.s"
	@echo "... src/mapping/impl/net/minecraft/util/AxisAlignedBB.o"
	@echo "... src/mapping/impl/net/minecraft/util/AxisAlignedBB.i"
	@echo "... src/mapping/impl/net/minecraft/util/AxisAlignedBB.s"
	@echo "... src/mapping/impl/net/minecraft/util/MovingObjectPosition.o"
	@echo "... src/mapping/impl/net/minecraft/util/MovingObjectPosition.i"
	@echo "... src/mapping/impl/net/minecraft/util/MovingObjectPosition.s"
	@echo "... src/mapping/impl/net/minecraft/util/Timer.o"
	@echo "... src/mapping/impl/net/minecraft/util/Timer.i"
	@echo "... src/mapping/impl/net/minecraft/util/Timer.s"
	@echo "... src/mapping/impl/net/minecraft/util/Vec3.o"
	@echo "... src/mapping/impl/net/minecraft/util/Vec3.i"
	@echo "... src/mapping/impl/net/minecraft/util/Vec3.s"
	@echo "... src/mapping/impl/org/lwjgl/input/Mouse.o"
	@echo "... src/mapping/impl/org/lwjgl/input/Mouse.i"
	@echo "... src/mapping/impl/org/lwjgl/input/Mouse.s"
	@echo "... src/ui/KeyManager.o"
	@echo "... src/ui/KeyManager.i"
	@echo "... src/ui/KeyManager.s"
	@echo "... src/ui/PhantomWindow.o"
	@echo "... src/ui/PhantomWindow.i"
	@echo "... src/ui/PhantomWindow.s"
	@echo "... src/utils/ImGuiUtils.o"
	@echo "... src/utils/ImGuiUtils.i"
	@echo "... src/utils/ImGuiUtils.s"
	@echo "... src/utils/JvmUtils.o"
	@echo "... src/utils/JvmUtils.i"
	@echo "... src/utils/JvmUtils.s"
	@echo "... src/utils/MCUtils.o"
	@echo "... src/utils/MCUtils.i"
	@echo "... src/utils/MCUtils.s"
	@echo "... src/utils/MSTimer.o"
	@echo "... src/utils/MSTimer.i"
	@echo "... src/utils/MSTimer.s"
	@echo "... src/utils/MathHelper.o"
	@echo "... src/utils/MathHelper.i"
	@echo "... src/utils/MathHelper.s"
	@echo "... src/utils/MiscUtils.o"
	@echo "... src/utils/MiscUtils.i"
	@echo "... src/utils/MiscUtils.s"
	@echo "... src/utils/XUtils.o"
	@echo "... src/utils/XUtils.i"
	@echo "... src/utils/XUtils.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_impl_opengl3.o"
	@echo "... vendor/imgui/imgui_impl_opengl3.i"
	@echo "... vendor/imgui/imgui_impl_opengl3.s"
	@echo "... vendor/imgui/imgui_impl_sdl.o"
	@echo "... vendor/imgui/imgui_impl_sdl.i"
	@echo "... vendor/imgui/imgui_impl_sdl.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

